### ISSUE TITLE
Questions about data

### ISSUE THREAD

**Issue by Vincy-Ying** [ayushayt/ImAiR#1]
Thanks for your project.
I have some questions. 1）The link of dataset may be valid, can you send me it？ 2）How to run the project, just run each python file?
Thanks.

**Comment by ayushayt** [comment]
Thanks for your interest in our work. 
The dataset can be found on the link https://drive.google.com/drive/folders/1NPv1mcy2PzXmlze7-2-Gn53mt3dadC5R

X_train.npy contains recordings from 40 subjects (15600 data samples) each of dimension 155*6 (155 is the time samples and 6 is the number of samples), Y_train.npy contains corresponding labels (0 for A, 1 for B, and so on..)

Similarly X_test.npy and Y_test.npy contain recordings from 10 subjects (5850 data points) for testing.

Just running each python script individually is sufficient.
